language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8

script:
  - sbt clean testGen/gen test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
