language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
script:
  - sbt clean test scalafmtTest

sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/sbt-scalafmt
    - $HOME/.coursier/cache
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete