language: scala
scala:
  - 2.12.8
jdk:
  - openjdk11
script:
  - sbt clean test benchmarks/compile
  - sbt scalafmtCheckAll

sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/sbt-scalafmt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
