name: Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run Tests
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: ;+compile;test;benchmarks/compile

  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Checking your code with scala fmt
        uses: openlawteam/scalafmt-ci@v2
        with:
          args: "--list"

