name: Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run Tests
        uses: lokkju/github-action-sbt@11-1.3.0-2.12.10
        with:
          commands: ;+compile;test;benchmarks/compile;scalafmt

